/*
  Copyright 2011, Florent Lamiraux, CNRS

  This file is part of dynamic-graph-corba.
  dynamic-graph-corba is free software: you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public License
  as published by the Free Software Foundation, either version 3 of
  the License, or (at your option) any later version.

  dynamic-graph-corba is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Lesser Public License for more details.  You should have
  received a copy of the GNU Lesser General Public License along with
  dynamic-graph-corba. If not, see <http://www.gnu.org/licenses/>.
*/

module dynamicGraph {
  typedef sequence<double> DoubleSeq;
  typedef sequence<DoubleSeq> SeqOfDoubleSeq;
  typedef sequence<long> SeqOfRank;

  interface NotifyCallback {
    //oneway
    void notifyClient ();
  };

  interface CorbaSignal {
    void readVector (in string signalName, out DoubleSeq value);
    void readMatrix (in string signalName, out SeqOfDoubleSeq value);
    void readMatrixHomogeneous (in string signalName, out SeqOfDoubleSeq value);

    long createOutputVectorSignal (in string signalNameCorba);
    long createInputVectorSignal (in string signalNameCorba);
    void readInputVectorSignal (in long signalRank, out DoubleSeq value);
    void readSeqInputVectorSignal (in SeqOfRank signalRanks,
				   out SeqOfDoubleSeq values);
    void writeOutputVectorSignal (in long signalRank, in DoubleSeq value);

    // RegisterCallback
    void registerClient (in NotifyCallback client, in string clientName);
    void unregisterClient (in string clientName);
  };
};
